# See documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
project_name: multi-profile
build:
  skip: true
release:
  github:
  prerelease: auto
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
