# See documentation at http://goreleaser.com

project_name: multi-profile

#build:
#  skip: true

builds:
  - skip: true

#builds:
#  - env:
#      - CGO_ENABLED=0
#    goos:
#      - linux
#    skip: true

#release:
#  github:
#  prerelease: auto

#archives:
#  - replacements:
#      linux: Linux

#checksum:
#  name_template: 'checksums.txt'

#snapshot:
#  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
