name: build
on:
  push:
    branches:
    tags-ignore:
      - '*'
  pull_request:
    branches:
env:
  GO111MODULE: "on"
jobs:
  build:
    name: build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -count=3 -race ./...
