on: [push, pull_request]
name: CI CD
env:
  GO111MODULE: "on"
jobs:
  pipeline:
    name: pipeline
#    strategy:
#      matrix:
#        go-version: [ 1.14.x, 1.15.x ]
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
#    runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
#          go-version: ${{ matrix.go-version }}
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -count=3 -race ./...
